name: Bug Report
about: Report a reproducible issue with this project
labels: bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        Please complete the fields below to help us reproduce and fix the issue more quickly.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      render: markdown
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps To Reproduce
      description: |
        Provide step-by-step instructions for how to reproduce the issue.
      placeholder: |
        1. Go to '...'
        2. Run '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: Describe what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Tell us about your environment. Include versions where applicable.
      placeholder: |
        Payload Auth version:
        Payload version:
        Node version:
        Database type and version:
        OS:
    validations:
      required: true

  - type: input
    id: reproduction-url
    attributes:
      label: Reproduction URL (optional)
      description: |
        If you have a minimal reproduction repository or URL, please link it here. This helps us troubleshoot faster.
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, logs, or screenshots about the problem here.
    validations:
      required: false
