name: Feature Request
about: Suggest an idea or enhancement for this project
labels: enhancement
body:
  - type: markdown
    attributes:
      value: |
        Thank you for contributing an idea to improve this project!
        Please answer the questions below so we can better understand your request.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Explain the problem this feature would solve or the use case it enables.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe alternative solutions or features you've considered.
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
